// Auto-generated by scripts/capture-fixtures.mjs — do not edit by hand.
export { collapsedGroupFixture } from './collapsed-group';
export { emptyFixture } from './empty';
export { iamRoleFixture } from './iam-role';
export { iamStackFixture } from './iam-stack';
export { wiredStackFixture } from './wired-stack';
