/**
 * End-to-End Integration Test: IAM Stack Composition Pipeline
 *
 * Spawns the real `lace module serve` binary and exercises the full
 * registry→download→compose pipeline through gRPC:
 *
 *   - Drop single leaf module (parsed from real Terraform, has resources)
 *   - Compose step-by-step: drop 3 leaf modules + connect
 *   - Drop full IAM stack composite (5-module bundle, flattens to 3 nodes)
 *   - Undo/redo after composition
 *   - Session persistence (save + close + reopen)
 *
 * Prerequisites: `lace` binary installed (set LACE_BINARY or have it in PATH).
 *
 * Fixtures are real Terraform modules parsed by the CLI module parser,
 * generated by: lace-cli/internal/module/testbundles/export_test.go
 */

import { describe, test, expect, beforeAll, afterEach } from 'vitest';
import { spawn, execSync, type ChildProcess } from 'child_process';
import { join } from 'path';
import { mkdtempSync, readFileSync, rmSync } from 'fs';
import { tmpdir } from 'os';

import { LaceClient } from '../../utilities/engine/grpc-client';

/* ── Binary resolution ── */

function resolveBinary(): string {
  if (process.env.LACE_BINARY) {
    return process.env.LACE_BINARY;
  }
  try {
    return execSync('which lace', { encoding: 'utf-8' }).trim();
  } catch {
    // not found
  }
  throw new Error(
    [
      'lace binary not found.',
      '',
      'Install it:',
      '  wget https://releases.lace.cloud/lace-cli-linux-amd64 -O lace',
      '  chmod +x lace && sudo mv lace /usr/local/bin/',
      '',
      'Or set LACE_BINARY=/path/to/lace before running tests.',
    ].join('\n'),
  );
}

/* ── Server lifecycle ── */

async function spawnServer(binary: string): Promise<{ process: ChildProcess; client: LaceClient }> {
  const proc = spawn(binary, ['module', 'serve'], {
    stdio: ['pipe', 'pipe', 'pipe'],
  });

  const port = await new Promise<number>((resolve, reject) => {
    const timeout = setTimeout(
      () => reject(new Error('Timed out waiting for LACE_GRPC_PORT')),
      10000,
    );
    let buffer = '';
    proc.stdout!.on('data', (chunk: Buffer) => {
      buffer += chunk.toString();
      const match = buffer.match(/LACE_GRPC_PORT=(\d+)/);
      if (match) {
        clearTimeout(timeout);
        resolve(Number(match[1]));
      }
    });
    proc.on('error', (err) => {
      clearTimeout(timeout);
      reject(err);
    });
    proc.on('exit', (code) => {
      clearTimeout(timeout);
      reject(new Error(`Process exited with code ${code} before reporting port`));
    });
  });

  const client = new LaceClient(port);
  return { process: proc, client };
}

/* ── Fixture loader ── */

const FIXTURES_DIR = join(__dirname, 'fixtures');

function loadFixture(name: string): Buffer {
  return readFileSync(join(FIXTURES_DIR, name));
}

/* ── Tests ── */

describe('E2E: IAM Stack Composition Pipeline', () => {
  let binary: string;
  let proc: ChildProcess | undefined;
  let client: LaceClient | undefined;

  beforeAll(() => {
    binary = resolveBinary();
  });

  afterEach(async () => {
    try {
      client?.dispose();
    } catch {
      // ignore
    }
    try {
      proc?.kill();
    } catch {
      // ignore
    }
    proc = undefined;
    client = undefined;
  });

  test('drop single leaf module (iam-role)', async () => {
    const srv = await spawnServer(binary);
    proc = srv.process;
    client = srv.client;

    await client.initialize('0.1.0');

    const tmpDir = mkdtempSync(join(tmpdir(), 'lace-e2e-'));
    try {
      const canvas = await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'leaf-test',
      });
      expect(canvas.nodes).toHaveLength(0);

      // Drop single leaf module — real Terraform with 1 resource
      const cv = await client.dropBundle({
        deploy_bundle: loadFixture('iam-role.bundle'),
      });

      // 1 resource → 1 resource node on canvas
      expect(cv.nodes).toHaveLength(1);
      expect(cv.nodes[0].kind).toBe('resource');

      // Query node config — verify instance resolves
      const config = await client.queryNodeConfig({
        instance_id: cv.nodes[0].id,
      });
      expect(config.instance_id).toBe(cv.nodes[0].id);

      await client.shutdown();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test('compose step-by-step: drop 3 leaf modules + connect', async () => {
    const srv = await spawnServer(binary);
    proc = srv.process;
    client = srv.client;

    await client.initialize('0.1.0');

    const tmpDir = mkdtempSync(join(tmpdir(), 'lace-e2e-'));
    try {
      await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'compose-test',
      });

      // Drop iam-role (1 resource node)
      const cv1 = await client.dropBundle({
        deploy_bundle: loadFixture('iam-role.bundle'),
      });
      expect(cv1.nodes).toHaveLength(1);
      const roleNodeId = cv1.nodes[0].id;

      // Drop iam-policy (2 resource nodes)
      const cv2 = await client.dropBundle({
        deploy_bundle: loadFixture('iam-policy.bundle'),
      });
      expect(cv2.nodes).toHaveLength(2);
      const policyNodeId = cv2.nodes.find((n) => n.id !== roleNodeId)!.id;

      // Drop iam-policy-attachment (3 resource nodes)
      const cv3 = await client.dropBundle({
        deploy_bundle: loadFixture('iam-policy-attachment.bundle'),
      });
      expect(cv3.nodes).toHaveLength(3);
      const attachNodeId = cv3.nodes.find((n) => n.id !== roleNodeId && n.id !== policyNodeId)!.id;

      // All 3 are resource nodes
      for (const node of cv3.nodes) {
        expect(node.kind).toBe('resource');
      }

      // Connect role -> attachment (role_name output -> role_name input)
      const cv4 = await client.connect({
        source: roleNodeId,
        target: attachNodeId,
        source_output: 'role_name',
        target_input: 'role_name',
      });
      expect(cv4.edges.length).toBeGreaterThanOrEqual(1);

      // Connect policy -> attachment (policy_arn output -> policy_arn input)
      const cv5 = await client.connect({
        source: policyNodeId,
        target: attachNodeId,
        source_output: 'policy_arn',
        target_input: 'policy_arn',
      });
      expect(cv5.edges.length).toBeGreaterThanOrEqual(2);
      expect(cv5.nodes).toHaveLength(3);

      await client.shutdown();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test('drop full iam_stack composite', async () => {
    const srv = await spawnServer(binary);
    proc = srv.process;
    client = srv.client;

    await client.initialize('0.1.0');

    const tmpDir = mkdtempSync(join(tmpdir(), 'lace-e2e-'));
    try {
      await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'iam-stack-test',
      });

      // Drop the full IAM stack composite (flattens to 3 leaf nodes)
      const cv = await client.dropBundle({
        deploy_bundle: loadFixture('iam-stack.bundle'),
      });

      // 3 nodes: iam_role, policy, attachment (flattened from composite)
      expect(cv.nodes).toHaveLength(3);
      const nodeIds = new Set(cv.nodes.map((n) => n.id));
      expect(nodeIds.has('iam_role')).toBe(true);
      expect(nodeIds.has('policy')).toBe(true);
      expect(nodeIds.has('attachment')).toBe(true);

      for (const node of cv.nodes) {
        expect(node.kind).toBe('module');
        // Every node should have a computed layout position
        expect(node.position).toBeDefined();
        expect(typeof node.position.x).toBe('number');
        expect(typeof node.position.y).toBe('number');
      }

      // Pre-wired bindings: iam_role→attachment (role_name) and policy→attachment (policy_arn)
      expect(cv.edges.length).toBeGreaterThanOrEqual(2);
      const edgeKey = (e: {
        source: string;
        target: string;
        source_output: string;
        target_input: string;
      }) => `${e.source}.${e.source_output}->${e.target}.${e.target_input}`;
      const edgeKeys = new Set(cv.edges.map(edgeKey));
      expect(edgeKeys.has('iam_role.role_name->attachment.role_name')).toBe(true);
      expect(edgeKeys.has('policy.policy_arn->attachment.policy_arn')).toBe(true);

      // Validate — should be clean
      const validation = await client.queryValidate();
      expect(validation.errors).toHaveLength(0);

      // Generate dry-run — should produce terraform files
      const gen = await client.sessionGenerate({
        output_dir: tmpDir,
        options: { dry_run: true },
      });
      const errors = (gen.diagnostics ?? []).filter(
        (d: { severity: string }) => d.severity === 'error',
      );
      expect(errors).toHaveLength(0);

      await client.shutdown();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test('undo/redo after composition', async () => {
    const srv = await spawnServer(binary);
    proc = srv.process;
    client = srv.client;

    await client.initialize('0.1.0');

    const tmpDir = mkdtempSync(join(tmpdir(), 'lace-e2e-'));
    try {
      await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'undo-redo-test',
      });

      // Drop IAM stack
      const cv = await client.dropBundle({
        deploy_bundle: loadFixture('iam-stack.bundle'),
      });
      expect(cv.nodes).toHaveLength(3);
      expect(cv.can_undo).toBe(true);

      // Undo — back to empty
      const undoCv = await client.undo();
      expect(undoCv.nodes).toHaveLength(0);
      expect(undoCv.can_redo).toBe(true);
      expect(undoCv.can_undo).toBe(false);

      // Redo — back to 3 nodes
      const redoCv = await client.redo();
      expect(redoCv.nodes).toHaveLength(3);
      expect(redoCv.can_undo).toBe(true);

      await client.shutdown();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test('compose: iam_role leaf + cloudwatch_logs_policy composite', async () => {
    // Simulates: download iam_role (leaf) and cloudwatch_logs_policy (composite)
    // separately from the registry, drop both, then connect role_name output
    // from iam_role to role_name input on cloudwatch_logs_policy.
    const srv = await spawnServer(binary);
    proc = srv.process;
    client = srv.client;

    await client.initialize('0.1.0');

    const tmpDir = mkdtempSync(join(tmpdir(), 'lace-e2e-'));
    try {
      await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'role-plus-composite-test',
      });

      // Drop iam_role leaf (1 resource → 1 resource node)
      const cv1 = await client.dropBundle({
        deploy_bundle: loadFixture('iam-role.bundle'),
      });
      expect(cv1.nodes).toHaveLength(1);
      expect(cv1.nodes[0].kind).toBe('resource');
      const roleNodeId = cv1.nodes[0].id;

      // Drop cloudwatch_logs_policy composite (2 child Uses → 2 module nodes)
      const cv2 = await client.dropBundle({
        deploy_bundle: loadFixture('cloudwatch-logs-policy.bundle'),
      });
      expect(cv2.nodes).toHaveLength(3); // 1 resource + 2 modules

      // The composite flattens to 2 module nodes (policy + attachment).
      const compositeNodes = cv2.nodes.filter((n) => n.id !== roleNodeId);
      expect(compositeNodes).toHaveLength(2);
      const compositeIds = new Set(compositeNodes.map((n) => n.id));
      expect(compositeIds.has('policy')).toBe(true);
      expect(compositeIds.has('attachment')).toBe(true);

      for (const node of compositeNodes) {
        expect(node.kind).toBe('module');
        // Composite children should have computed layout positions
        expect(node.position).toBeDefined();
        expect(typeof node.position.x).toBe('number');
        expect(typeof node.position.y).toBe('number');
      }

      // Pre-wired edge: policy.policy_arn → attachment.policy_arn
      const preWiredEdge = cv2.edges.find(
        (e) =>
          e.source === 'policy' &&
          e.target === 'attachment' &&
          e.source_output === 'policy_arn' &&
          e.target_input === 'policy_arn',
      );
      expect(preWiredEdge).toBeDefined();

      // Find the attachment node by id — the flattened composite names
      // its child Uses by their instance IDs (policy, attachment).
      const attachmentNode = compositeNodes.find((n) => n.id === 'attachment');
      expect(attachmentNode).toBeDefined();
      const attachmentNodeId = attachmentNode!.id;

      // Connect iam_role resource → attachment module (role_name → role_name)
      const cv3 = await client.connect({
        source: roleNodeId,
        target: attachmentNodeId!,
        source_output: 'role_name',
        target_input: 'role_name',
      });

      // Should have more edges now
      expect(cv3.edges.length).toBeGreaterThan(cv2.edges.length);

      // Validate
      const validation = await client.queryValidate();
      expect(validation.errors).toHaveLength(0);

      // Generate dry-run
      const gen = await client.sessionGenerate({
        output_dir: tmpDir,
        options: { dry_run: true },
      });
      const errors = (gen.diagnostics ?? []).filter(
        (d: { severity: string }) => d.severity === 'error',
      );
      expect(errors).toHaveLength(0);

      await client.shutdown();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test('session persistence: save + close + reopen', async () => {
    const srv = await spawnServer(binary);
    proc = srv.process;
    client = srv.client;

    await client.initialize('0.1.0');

    const tmpDir = mkdtempSync(join(tmpdir(), 'lace-e2e-'));
    try {
      // Open session and drop IAM stack
      await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'persist-test',
      });
      const cv = await client.dropBundle({
        deploy_bundle: loadFixture('iam-stack.bundle'),
      });
      const nodeCount = cv.nodes.length;
      const edgeCount = cv.edges.length;

      expect(nodeCount).toBeGreaterThan(0);

      // Save and close
      const saveResult = await client.sessionSave();
      expect(saveResult.saved).toBe(true);

      await client.sessionClose();

      // Reopen same path
      const reopened = await client.sessionOpen({
        file_path: tmpDir,
        workspace_name: 'persist-test',
      });

      expect(reopened.nodes).toHaveLength(nodeCount);
      expect(reopened.edges).toHaveLength(edgeCount);

      await client.shutdown();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});
